POST /api/0.1/assets?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 3673
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "assetType": "claimRights", 
    "classification": {
      "scheme": "CAV", 
      "id": "39513200-3", 
      "description": "Земельні ділянки"
    }, 
    "title": "Земля для космодрому", 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV", 
          "id": "39513200-3", 
          "description": "Cartons"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }, 
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV", 
          "id": "39513200-3", 
          "description": "Cartons"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "unit": {
      "code": "39513200-3", 
      "name": "item"
    }, 
    "address": {
      "countryName": "Україна", 
      "postalCode": "79000", 
      "region": "м. Київ", 
      "streetAddress": "вул. Банкова 1", 
      "locality": "м. Київ"
    }, 
    "debt": {
      "agreementNumber": "42", 
      "debtCurrencyValue": {
        "currency": "USD", 
        "amount": 100
      }, 
      "value": {
        "currency": "UAH", 
        "amount": 1
      }, 
      "dateSigned": "2017-08-16T12:30:17.615196+03:00", 
      "debtorType": "legalPerson"
    }, 
    "assetCustodian": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "quantity": 5
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea.openprocurement.net/api/0.1/assets/75b11ba80dc74164ab8862e243874933
X-Content-Type-Options: nosniff
{
  "access": {
    "token": "1fce0707515b423681f82f9d639baa0c"
  }, 
  "data": {
    "status": "draft", 
    "assetType": "claimRights", 
    "classification": {
      "scheme": "CAV", 
      "description": "Земельні ділянки", 
      "id": "39513200-3"
    }, 
    "title": "Земля для космодрому", 
    "assetID": "UA-AR-DGF-2017-09-26-000002", 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV", 
          "description": "Cartons", 
          "id": "39513200-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "7e64a2e3a3e1476c8d7dc6cdcd511057", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }, 
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV", 
          "description": "Cartons", 
          "id": "39513200-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "d9536444955541f0ac7693bc647bb11b", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateModified": "2017-09-26T11:39:12.527629+03:00", 
    "owner": "broker", 
    "assetCustodian": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "address": {
      "postalCode": "79000", 
      "countryName": "Україна", 
      "streetAddress": "вул. Банкова 1", 
      "region": "м. Київ", 
      "locality": "м. Київ"
    }, 
    "date": "2017-09-26T11:39:12.522965+03:00", 
    "debt": {
      "agreementNumber": "42", 
      "debtCurrencyValue": {
        "currency": "USD", 
        "amount": 100.0
      }, 
      "dateSigned": "2017-08-16T12:30:17.615196+03:00", 
      "value": {
        "currency": "UAH", 
        "amount": 1.0
      }, 
      "debtorType": "legalPerson"
    }, 
    "id": "75b11ba80dc74164ab8862e243874933", 
    "unit": {
      "code": "39513200-3", 
      "name": "item"
    }, 
    "quantity": 5
  }
}

