GET /api/0.1/assets/b1845029a72a4077aeff912604721ee7 HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Host: lb.api-sandbox.registry.ea.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "pending", 
    "assetType": "claimRights", 
    "classification": {
      "scheme": "CAV", 
      "description": "Земельні ділянки", 
      "id": "39513200-3"
    }, 
    "title": "Земля для космодрому", 
    "assetID": "UA-AR-DGF-2018-01-09-000003", 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV", 
          "description": "Cartons", 
          "id": "39513200-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "ecc9f4ec8b524f51a21c2736724f7848", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }, 
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV", 
          "description": "Cartons", 
          "id": "39513200-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "5262128ff2d344a9b720227e724840db", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateModified": "2018-01-09T18:31:04.904205+02:00", 
    "owner": "broker", 
    "assetCustodian": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "address": {
      "postalCode": "79000", 
      "countryName": "Україна", 
      "streetAddress": "вул. Банкова 1", 
      "region": "м. Київ", 
      "locality": "м. Київ"
    }, 
    "date": "2018-01-09T18:31:04.903875+02:00", 
    "debt": {
      "agreementNumber": "42", 
      "debtCurrencyValue": {
        "currency": "USD", 
        "amount": 100.0
      }, 
      "dateSigned": "2017-08-16T12:30:17.615196+03:00", 
      "value": {
        "currency": "UAH", 
        "amount": 1.0
      }, 
      "debtorType": "legalPerson"
    }, 
    "id": "b1845029a72a4077aeff912604721ee7", 
    "unit": {
      "code": "39513200-3", 
      "name": "item"
    }, 
    "quantity": 5
  }
}

