GET /api/0.1/assets?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb.api-sandbox.registry.ea.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "next_page": {
    "path": "/api/0.1/assets?offset=2018-01-09T18%3A31%3A03.936033%2B02%3A00", 
    "uri": "http://lb.api-sandbox.registry.ea.openprocurement.net/api/0.1/assets?offset=2018-01-09T18%3A31%3A03.936033%2B02%3A00", 
    "offset": "2018-01-09T18:31:03.936033+02:00"
  }, 
  "data": [
    {
      "id": "6aa3093c0b00447abefcacf9a11da277", 
      "dateModified": "2018-01-09T18:31:03.936033+02:00"
    }
  ]
}

